# Generated by Django 3.0.1 on 2021-03-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=200, verbose_name='Post Name')),
                ('college_name', models.CharField(max_length=200, verbose_name='College Name')),
                ('vacancies', models.IntegerField(default=0, verbose_name='Vacancies')),
                ('salary_per_month', models.FloatField(verbose_name='Per Month Salary')),
                ('phd_required', models.BooleanField(default=True, verbose_name='PHD Required')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('website_url', models.URLField(verbose_name='Post URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Faculty Notifications',
            },
        ),
        migrations.CreateModel(
            name='PHDNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200, verbose_name='Program Name')),
                ('college_name', models.CharField(max_length=200, verbose_name='College Name')),
                ('stipend_available', models.BooleanField(default=True, verbose_name='Stipend Availability')),
                ('vacancies', models.IntegerField(default=0, verbose_name='Vacancies')),
                ('stipend_amount', models.FloatField(verbose_name='Stipend Amount')),
                ('program_fees', models.FloatField(verbose_name='Program Fees')),
                ('gate_required', models.BooleanField(default=True, verbose_name='Gate Exam Required')),
                ('ugc_net_required', models.BooleanField(default=False, verbose_name='UGCNET Exam Required')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('website_url', models.URLField(verbose_name='Program URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'PHD Notifications',
            },
        ),
    ]
